dist: trusty
language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  api_token:
    secure: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwlzLjANtGEMyh6tRVAA4\nvnCOX6RvwCsznyOUrCWUDWtEqxP2AxUeCyo0vBbhc3773pvKE3OVuJa+hFg4C3/n\nx7VAhCalojsv5NKWKmxOXmktmH/5yQdMY90qgQouHmPpvAKoY5iaPzvL8O1UALG9\nSbGbu4kMaIM5WN8xDg021sR9wTYre/BM/J6BaTFKNHfwTDqKMEUtJhXVNoEdsP0D\nR7zJownJ9Li2adFGeSy97riTlOtRWkTibQ/t5SVY+D/7JNZmNtbNldXhkBBZfSwO\n3MV9d9ZAai0gtNsWlPnWwSVn5UkFkqXJTZK6giy8JcxM3TEe/1eeaqp1wOQa2Lnh\nvmC5OVDptN6tb8UoCx5EdUtZB2n1GvNVnv0Dj1it3qBSSjw0KBZtZlpxeR1moMzr\nHQQPJElXgXCiRNaKi4NTbCJkhI7Npl0HpE+4Npc7dAqQXRvRiM0JaXHBmKeiz4KU\nRyQyXyJsBtYVEZFEsJT6qwTIA2kVbYhBJJOMB2XO9jLd7UDkYP2vp5B6ryOrM1s4\nhA1JSpt2d5jvqNl0toXCR6+IkXTNYui9XCCtM/apzl2uIwedAmwLoloAQaCYhqOd\nelqUEaS/GqQXkDuzZQSjG0bMF6jKmOK77y/H4SCBhrmPVTaRsig53eIWmSoHHbth\nugluQHOyIlkNrF4oqddd1pECAwEAAQ==
  on:
    branch: release
    tags: true
