FROM ubuntu:16.04
MAINTAINER SpaceInvasionLab <spaceinvasionlab@yandex.ru>

RUN apt update &&\
    apt-get install -y git openjdk-8-jdk-headless maven

ENV SPACE_INVASION_ROOT=/var/www/SpaceInvasion

RUN mkdir -p $SPACE_INVASION_ROOT
COPY . $SPACE_INVASION_ROOT
WORKDIR $SPACE_INVASION_ROOT

RUN mvn install
EXPOSE 80
