#!/bin/bash
# Production
psql -U "$POSTGRES_USER" -c "CREATE ROLE $PGUSER WITH SUPERUSER LOGIN ENCRYPTED PASSWORD '$PGPASSWORD';
CREATE DATABASE $PGDATABASE ENCODING 'utf8';
GRANT ALL ON DATABASE $PGDATABASE TO $PGUSER;"

# Test
psql -U "$POSTGRES_USER" -c "CREATE ROLE $PGTESTUSER WITH SUPERUSER LOGIN ENCRYPTED PASSWORD '$PGTESTPASSWORD';
CREATE DATABASE $PGTESTDATABASE ENCODING 'utf8';
GRANT ALL ON DATABASE $PGTESTDATABASE TO $PGTESTUSER;"
